### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by Anonyfox** [tonini/alchemist-server#2]
If I understand this correctly, alchemist-server wants to be some kind of "middleware", against which others can implement editor-plugins? If so, are there already some examples how people can use this from a plugin author's point of view? sublime text preferred :)

**Comment by tonini** [comment]
Hi,

The only one which I know using the Alchemist-Server so far is https://github.com/sanmiguel/helpex.vim
I can't give you an example for sublime text because I have no experience with it, I'm an Emacs kind of guy. ;-)

But you could have a look at https://github.com/vishnevskiy/ElixirSublime where for example `mix` get's called in as a process too. The Alchemist-Server is just an CLI tool too, so you just create a process with it and sending and receive informations.

**Comment by bryanjos** [comment]
I've been playing around with using alchemist-server in a Sublime Text plugin for the past couple of days https://github.com/bryanjos/SublimeAlchemist. Working with alchemist-server has been going well so far. I've only really tried listing mix tasks and modules so far though. The thing I finally tackled today was being able to communicate via STDIN and STDOUT multiple times in Python. I ended up using a library called Pexpect. I think that might be one of the biggest hurdles which is why I'm mentioning it here.

Anyways, you can take a look there and get some ideas if you want to try building a plugin in ST. I've also took a look at the code in ElixirSublime to get some ideas as well.

**Comment by Anonyfox** [comment]
Awesome @bryanjos ! Would you mind pushing this early version to https://packagecontrol.io ? The more people can get their hands on it easily, the better the feedback I'd say. 

I'll close this issue for now... but a little love for sublime is just great for us non-emacs-guys out there ;)

**Comment by bryanjos** [comment]
@Anonyfox maybe I'll try that. Now I'm wondering if ElixirSublime has any plans to integrate alchemist-server into it. I'll ask!
